"use client";
import React, { useState, useCallback, useMemo } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Globe,
  Loader2,
  AlertTriangle,
  XCircle,
  CheckCircle2,
  Gauge,
  FileText,
  Image as ImageIcon,
  Link2,
  Braces,
  Download,
  Sparkles,
  RefreshCcw,
  ExternalLink,
} from "lucide-react";
import { CopyButton } from "./ui/CopyButton";

interface Issue {
  severity: "critical" | "warning" | "passed";
  title: string;
  detail: string;
  fix: string;
}

interface AnalysisResult {
  requestedUrl: string;
  finalUrl: string;
  fetchedAt: string;
  response: { status: number; contentType: string; sizeBytes: number };
  analysis: {
    score: number;
    grade: string;
    counts: Record<string, number>;
    title: string;
    metaDescription: string;
    metaKeywords: string;
    canonical: string;
    viewport: string;
    robotsMeta: string;
    lang: string;
    charsetDeclared: boolean;
    og: { ogTitle: string; ogDesc: string; ogImage: string };
    twitterCard: string;
    hreflang: string[];
    h1s: string[];
    schemaTypes: string[];
  };
  issues: Issue[];
}

const severityStyles: Record<
  Issue["severity"],
  { icon: React.ElementType; label: string; box: string; badge: string; iconClass: string }
> = {
  critical: {
    icon: XCircle,
    label: "Critical",
    box: "border-rose-500/40 bg-rose-500/8",
    badge: "bg-rose-500/20 text-rose-300 border-rose-500/40",
    iconClass: "text-rose-400",
  },
  warning: {
    icon: AlertTriangle,
    label: "Warning",
    box: "border-amber-500/40 bg-amber-500/8",
    badge: "bg-amber-500/20 text-amber-300 border-amber-500/40",
    iconClass: "text-amber-400",
  },
  passed: {
    icon: CheckCircle2,
    label: "Passed",
    box: "border-emerald-500/40 bg-emerald-500/8",
    badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
    iconClass: "text-emerald-400",
  },
};

function safeHostname(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
}

export const UrlAnalyzer: React.FC = () => {
  const [url, setUrl] = useState("https://example.com");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<AnalysisResult | null>(null);

  const runAnalysis = useCallback(async (targetUrl: string) => {
    setLoading(true);
    setError("");
    setResult(null);
    try {
      const res = await fetch("/api/seo/fetch", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ url: targetUrl }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setError(data.error || "Analysis failed. Check the URL and try again.");
        return;
      }
      setResult(data as AnalysisResult);
    } catch {
      setError("Network error while analyzing the URL. Please try again.");
    } finally {
      setLoading(false);
    }
  }, []);

  const handleSubmit = () => {
    const trimmed = url.trim();
    if (!trimmed) {
      setError("Please enter a website URL.");
      return;
    }
    void runAnalysis(trimmed);
  };

  // Memoize to avoid re-computing on every render
  const fixedHead = useMemo(() => {
    if (!result) return "";
    const host = result.finalUrl.replace(/\/$/, "");
    const words = result.analysis.title
      .split(/[\s|–—-]+/)
      .filter(Boolean)
      .slice(0, 7)
      .join(" ");
    const hostname = safeHostname(result.finalUrl).split(".")[0] || "Website";
    const suggestedTitle =
      result.analysis.title && result.analysis.title.length <= 60
        ? result.analysis.title
        : `${words} — ${hostname}`;
    const suggestedDesc =
      result.analysis.metaDescription.length >= 70 &&
      result.analysis.metaDescription.length <= 165
        ? result.analysis.metaDescription
        : `Explore ${words || "our"} — comprehensive information, services and contact details at ${host}. Reach out for more.`;
    return `<!-- Corrected <head> block regenerated by the URL Analyzer for ${result.finalUrl} -->
<title>${suggestedTitle}</title>
<meta name="description" content="${suggestedDesc}" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta charset="utf-8" />
<link rel="canonical" href="${host}/" />
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large" />
<meta property="og:type" content="website" />
<meta property="og:url" content="${host}/" />
<meta property="og:title" content="${suggestedTitle}" />
<meta property="og:description" content="${suggestedDesc}" />
<meta name="twitter:card" content="summary_large_image" />`;
  }, [result]);

  const handleDownloadFixed = () => {
    if (!result) return;
    const blob = new Blob([fixedHead], { type: "text/html;charset=utf-8" });
    const urlObj = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = urlObj;
    a.download = "corrected-seo-head.html";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(urlObj);
  };

  const counts = result?.analysis.counts;
  const severityOrder: Issue["severity"][] = ["critical", "warning", "passed"];
  const criticalCount = result?.issues.filter((i) => i.severity === "critical").length ?? 0;
  const warningCount = result?.issues.filter((i) => i.severity === "warning").length ?? 0;
  const passedCount = result?.issues.filter((i) => i.severity === "passed").length ?? 0;

  return (
    <div className="bg-white/5 border border-white/10 p-6 sm:p-8 rounded-2xl space-y-6 shadow-2xl">
      {/* Header */}
      <div className="border-b border-white/10 pb-4 space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-white border border-white/20 text-[10px] font-mono uppercase tracking-widest">
          <Globe className="w-3.5 h-3.5 text-emerald-400" />
          <span>Live Website URL Analyzer</span>
        </div>
        <h3 className="text-xl sm:text-2xl font-black text-white tracking-tight uppercase">
          Fetch Any Website URL &amp; Run an On-Page SEO Scan
        </h3>
        <p className="text-xs text-white/70 max-w-3xl leading-relaxed">
          Enter a live website link — the server fetches the real page and scans title,
          description, headings, images, structured data, links and more. Every finding
          includes a concrete fix plus a ready-to-paste corrected{" "}
          <span className="font-mono text-emerald-300">&lt;head&gt;</span> block.
        </p>
      </div>

      {/* URL Input */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <label htmlFor="url-analyzer-input" className="sr-only">
            Website URL to analyze
          </label>
          <Globe className="w-4 h-4 text-white/40 absolute left-3.5 top-3.5" />
          <input
            id="url-analyzer-input"
            name="url"
            type="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
            placeholder="https://yourwebsite.com"
            aria-label="Website URL to analyze"
            className="w-full bg-black border border-white/20 rounded-xl pl-10 pr-4 py-2.5 text-sm font-mono text-white placeholder-white/30 focus:outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-400/20 transition-all input-glow"
          />
        </div>
        <button
          onClick={handleSubmit}
          disabled={loading}
          className="px-6 py-2.5 bg-white text-black font-mono font-bold text-xs uppercase tracking-wider rounded-xl hover:bg-emerald-400 transition-all flex items-center justify-center gap-2 shadow-lg active:scale-95 disabled:opacity-60 disabled:cursor-not-allowed"
        >
          {loading ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Sparkles className="w-4 h-4 text-emerald-600" />
          )}
          {loading ? "Scanning..." : "Analyze URL"}
        </button>
      </div>

      {/* Error */}
      {error && (
        <div className="p-3 bg-rose-500/15 border border-rose-500/30 rounded-xl text-xs font-mono text-rose-300 flex items-center gap-2">
          <XCircle className="w-4 h-4 shrink-0" />
          {error}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div
          className="flex flex-col items-center justify-center py-16 gap-4"
          role="status"
          aria-label="Analyzing URL"
        >
          <div className="relative w-12 h-12">
            <div className="w-12 h-12 rounded-full border-2 border-white/10 border-t-emerald-400 animate-spin" />
            <div className="absolute inset-2 rounded-full border border-emerald-400/20 border-t-emerald-400/60 animate-spin" style={{ animationDirection: "reverse", animationDuration: "0.8s" }} />
          </div>
          <div className="text-center">
            <p className="text-xs font-mono text-white/50 uppercase tracking-widest">Fetching page &amp; running SEO scan…</p>
            <p className="text-[10px] font-mono text-white/30 mt-1">This may take 5–15 seconds</p>
          </div>
        </div>
      )}

      <AnimatePresence>
        {result && !loading && (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.35 }}
            className="space-y-6"
          >
            {/* Score Summary Bar */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {/* Grade */}
              <div className="p-4 bg-zinc-900/80 border border-white/10 rounded-2xl flex items-center gap-3">
                <div
                  className={`w-14 h-14 rounded-2xl flex flex-col items-center justify-center font-mono font-black text-lg border shrink-0 ${
                    result.analysis.grade.startsWith("A")
                      ? "bg-emerald-500/20 text-emerald-300 border-emerald-500/40"
                      : result.analysis.grade.startsWith("B")
                      ? "bg-teal-500/20 text-teal-300 border-teal-500/40"
                      : result.analysis.grade.startsWith("C")
                      ? "bg-amber-500/20 text-amber-300 border-amber-500/40"
                      : "bg-rose-500/20 text-rose-300 border-rose-500/40"
                  }`}
                >
                  <span>{result.analysis.grade}</span>
                  <span className="text-[8px] opacity-70">{result.analysis.score}/100</span>
                </div>
                <div className="text-xs font-mono">
                  <div className="text-white font-bold">On-Page Score</div>
                  <div className="text-white/50 mt-0.5">HTTP {result.response.status}</div>
                  <div className="text-white/40 break-all text-[10px] mt-0.5">
                    {safeHostname(result.finalUrl)}
                  </div>
                </div>
              </div>

              {/* Issues Summary */}
              <div className="p-4 bg-zinc-900/80 border border-white/10 rounded-2xl space-y-2">
                <div className="text-[10px] font-mono uppercase text-white/40 font-bold">Issues</div>
                <div className="flex flex-col gap-1.5">
                  <div className="flex items-center justify-between text-xs font-mono">
                    <span className="text-rose-300 flex items-center gap-1"><XCircle className="w-3 h-3" /> Critical</span>
                    <span className="font-black text-rose-300">{criticalCount}</span>
                  </div>
                  <div className="flex items-center justify-between text-xs font-mono">
                    <span className="text-amber-300 flex items-center gap-1"><AlertTriangle className="w-3 h-3" /> Warnings</span>
                    <span className="font-black text-amber-300">{warningCount}</span>
                  </div>
                  <div className="flex items-center justify-between text-xs font-mono">
                    <span className="text-emerald-300 flex items-center gap-1"><CheckCircle2 className="w-3 h-3" /> Passed</span>
                    <span className="font-black text-emerald-300">{passedCount}</span>
                  </div>
                </div>
              </div>

              {/* Content Stats */}
              <div className="p-4 bg-zinc-900/80 border border-white/10 rounded-2xl grid grid-cols-2 gap-2 text-center">
                {[
                  { icon: FileText, label: "Words", value: counts?.words ?? 0 },
                  { icon: Gauge, label: "H1 Tags", value: counts?.h1 ?? 0 },
                  { icon: ImageIcon, label: "Images", value: counts?.images ?? 0 },
                  { icon: Link2, label: "Int. Links", value: counts?.internalLinks ?? 0 },
                ].map((stat) => (
                  <div key={stat.label} className="flex flex-col items-center gap-0.5">
                    <stat.icon className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-lg font-black text-white font-mono leading-none">
                      {stat.value}
                    </span>
                    <span className="text-[8px] font-mono uppercase tracking-wide text-white/40 leading-none">
                      {stat.label}
                    </span>
                  </div>
                ))}
              </div>

              {/* Structured Data */}
              <div className="p-4 bg-zinc-900/80 border border-white/10 rounded-2xl flex items-start gap-3">
                <Braces className="w-7 h-7 text-emerald-400 shrink-0 mt-0.5" />
                <div className="text-xs font-mono space-y-1.5 min-w-0">
                  <div className="text-white font-bold uppercase text-[10px] tracking-wider">
                    Structured Data
                  </div>
                  <div className="text-white/60 break-words text-[10px] leading-relaxed">
                    {result.analysis.schemaTypes.length > 0
                      ? result.analysis.schemaTypes.join(", ")
                      : "None detected"}
                  </div>
                  {(counts?.imagesNoAlt ?? 0) > 0 && (
                    <div className="text-amber-300 text-[10px]">
                      {counts?.imagesNoAlt} image{(counts?.imagesNoAlt ?? 0) !== 1 ? "s" : ""} missing alt text
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Found Metadata */}
            {result.analysis.title && (
              <div className="p-4 bg-zinc-900/80 border border-white/10 rounded-2xl space-y-2">
                <div className="text-[10px] font-mono uppercase font-bold text-white/50 tracking-wider mb-2">
                  Detected Metadata
                </div>
                <div className="space-y-2 text-xs font-mono">
                  <div className="flex items-start gap-2">
                    <span className="text-white/40 uppercase font-bold text-[10px] tracking-wide w-24 shrink-0 pt-0.5">Title</span>
                    <span className="text-emerald-300 break-all flex-1">{result.analysis.title}</span>
                    <span className="text-white/30 text-[10px] shrink-0">({result.analysis.counts.titleChars} chars)</span>
                  </div>
                  {result.analysis.metaDescription && (
                    <div className="flex items-start gap-2">
                      <span className="text-white/40 uppercase font-bold text-[10px] tracking-wide w-24 shrink-0 pt-0.5">Description</span>
                      <span className="text-white/70 break-all flex-1">{result.analysis.metaDescription}</span>
                      <span className="text-white/30 text-[10px] shrink-0">({result.analysis.counts.descriptionChars} chars)</span>
                    </div>
                  )}
                  {result.analysis.h1s.length > 0 && (
                    <div className="flex items-start gap-2">
                      <span className="text-white/40 uppercase font-bold text-[10px] tracking-wide w-24 shrink-0 pt-0.5">H1</span>
                      <span className="text-white/70 flex-1">{result.analysis.h1s.slice(0, 2).join(" | ")}</span>
                    </div>
                  )}
                  {result.analysis.canonical && (
                    <div className="flex items-start gap-2">
                      <span className="text-white/40 uppercase font-bold text-[10px] tracking-wide w-24 shrink-0 pt-0.5">Canonical</span>
                      <a
                        href={result.analysis.canonical}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sky-400 hover:text-sky-300 break-all flex-1 flex items-center gap-1 transition-colors"
                      >
                        <span className="break-all">{result.analysis.canonical}</span>
                        <ExternalLink className="w-3 h-3 shrink-0" />
                      </a>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Findings */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-mono uppercase tracking-widest text-white/50 font-bold">
                  {result.issues.length} Findings
                </span>
                <div className="flex items-center gap-2">
                  {criticalCount > 0 && (
                    <span className="px-2 py-0.5 rounded text-[9px] font-mono font-bold bg-rose-500/20 text-rose-300 border border-rose-500/40">
                      {criticalCount} Critical
                    </span>
                  )}
                  {warningCount > 0 && (
                    <span className="px-2 py-0.5 rounded text-[9px] font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/40">
                      {warningCount} Warnings
                    </span>
                  )}
                </div>
              </div>

              {severityOrder.flatMap((severity) =>
                result.issues
                  .filter((i) => i.severity === severity)
                  .map((issue, idx) => {
                    const style = severityStyles[issue.severity];
                    const Icon = style.icon;
                    return (
                      <motion.div
                        key={`${severity}-${idx}`}
                        initial={{ opacity: 0, x: -8 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: Math.min(idx * 0.04, 0.5) }}
                        className={`p-4 rounded-xl border ${style.box} space-y-1.5`}
                      >
                        <div className="flex items-center gap-2">
                          <Icon className={`w-4 h-4 ${style.iconClass} shrink-0`} />
                          <span className="text-xs font-mono font-bold text-white flex-1">
                            {issue.title}
                          </span>
                          <span
                            className={`px-2 py-0.5 rounded text-[9px] font-mono font-bold uppercase border ${style.badge}`}
                          >
                            {style.label}
                          </span>
                        </div>
                        <p className="text-[11px] text-white/60 font-sans leading-relaxed pl-6">
                          {issue.detail}
                        </p>
                        <p className="text-[11px] text-emerald-300 font-mono leading-relaxed pl-6">
                          Fix: {issue.fix}
                        </p>
                      </motion.div>
                    );
                  })
              )}
            </div>

            {/* Corrected Head Block */}
            <div className="p-4 sm:p-5 bg-zinc-900/80 border border-emerald-500/30 rounded-2xl space-y-3">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2 text-xs font-mono font-bold uppercase tracking-wider text-white">
                  <RefreshCcw className="w-4 h-4 text-emerald-400" />
                  Corrected SEO Head Block (auto-regenerated)
                </div>
                <div className="flex items-center gap-2">
                  <CopyButton text={fixedHead} label="Copy" disabled={!result} />
                  <button
                    onClick={handleDownloadFixed}
                    className="px-3 py-1.5 bg-white text-black text-xs font-mono font-bold rounded-lg hover:bg-emerald-400 transition-colors flex items-center gap-1.5"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download
                  </button>
                </div>
              </div>
              <pre className="text-[11px] font-mono text-emerald-300 overflow-x-auto max-h-64 scrollbar-hide leading-relaxed p-3 bg-black/60 rounded-lg border border-white/5">
                {fixedHead}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};